name: Deploy NISP Nation to GitHub pages

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install XML Tools
      run: |
        sudo apt get update
        sudo apt-get install -qq libxml2-utils libsaxonb-java docbook-xml

    - name: Extract NISP data to YAML/Markdown files
      run: |
        mkdir -p _temp/standards/ _temp/schema/dtd/docbkx45/
        curl -o _temp/standards/standards.xml https://raw.githubusercontent.com/stavnstrup/nisp-tools/master/src/standards/standards.xml
        cp -r /usr/share/xml/docbook/schema/dtd/4.5/* _temp/schema/dtd/docbkx45/
        curl -o _temp/schema/dtd/stddb48.dtd https://raw.githubusercontent.com/stavnstrup/nisp-tools/master/src/schema/dtd/stddb48.dtd
        xmllint --noout --valid _temp/standards/standards.xml
        saxonb-xslt -ext:on _temp/standards/standards.xml _xsl/db2data.xsl
        rm -fR _temp/

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - name: Build
      run: hugo
