name: NISP Nation

on:
  push:
    branches:
    - master
  repository_dispatch:
    types: [build-nation]

jobs:
  build-deploy:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '11'

    - name: Install XML Tools
      run: |
        sudo apt install -qq libxml2-utils libsaxonb-java docbook-xml

    - name: Extract NISP data to YAML/Markdown files
      run: |
        mkdir -p _temp/standards/ _temp/schema/dtd/docbkx45/
        curl -o _temp/standards/standards.xml https://raw.githubusercontent.com/stavnstrup/nisp-tools/master/src/standards/standards.xml
        cp -r /usr/share/xml/docbook/schema/dtd/4.5/* _temp/schema/dtd/docbkx45/
        curl -o _temp/schema/dtd/stddb48.dtd https://raw.githubusercontent.com/stavnstrup/nisp-tools/master/src/schema/dtd/stddb48.dtd
        xmllint --noout --valid _temp/standards/standards.xml
        saxonb-xslt -ext:on _temp/standards/standards.xml _xsl/db2data.xsl
        rm -fR _temp/

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - run: npm ci

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.110.0'
        extended: true

    - run: hugo

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        external_repository: nispworld/nispworld.github.io
        publish_branch: master
        publish_dir: ./public
        user_name: 'nisp-bot'
        user_email: 'nisp-bot@nw3.dk'
        keep_files: true
        # cname: nisp.nw3.dk
